### ISSUE TITLE
Get error for `logs_and_screenshot_sections': undefined method `reporting_uid' f

### ISSUE THREAD

**Issue by Jirapong** [ph7/selenium-client#7]
The following error get after one of the selenium report fail.

/Users/jirapong/.gem/ruby/1.8/gems/selenium-client-1.2.16/lib/selenium/rspec/reporting/html_report.rb:22:in `logs_and_screenshot_sections': undefined method`reporting_uid' for #Spec::Example::ExampleProxy:0x1059b2ea8 (NoMethodError)
    from /Users/jirapong/.gem/ruby/1.8/gems/selenium-client-1.2.16/lib/selenium/rspec/reporting/html_report.rb:18:in `replace_placeholder_with_system_state_content'

**Comment by Jirapong** [comment]
fixture  out i forgot to include require 'selenium/rspec/spec_helper'
